### PR TITLE
Update how plugins are maintained

### PR DESCRIPTION
**Pull request by schloerke**
@timelyportfolio

I'm pinging you as you've been involved in updating a lot of the plugins.  This is currently not a working branch, rather a place to discuss how the package is structured.

I'd *really* like to update how the plugins are installed (and apply the same setup to the other leaflet packages). This incomplete branch is currently done with bower.

I believe the combo of webpack and npm would solve two main issues:
* what are custom bindings vs what are raw plugins
* where did each plugin actually get downloaded from (for easier updates in the future)

Webpack would be able to make independent bundles for each non-default plugin that would combine the custom bindings.  

-----------------------------------------------

Current question... 
* Where did awesome-markers come from?  I found a 2.0.2, but 2.0.3 is currently installed.

------------

Thank you for your help!

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@schloerke I really like the way you are thinking.  I have been doing manually, but surely there are some steps we can automate here.  `bower` no longer seems to be the method of choice for this and also gathers far more than we generally need.  I have begun to leverage npm https://unpkg.com to gather assets, but this is inconsistent.  For instance, with `Leaflet.draw`, the url https://unpkg.com/leaflet-draw will autopopulate with the most current version and point to the built JavaScript.  If we append the `/` to the url so https://unpkg.com/leaflet-draw/, then we get a directory listing.  In the case of `Leaflet.draw`, we also need other assets at https://unpkg.com/leaflet-draw/dist/.  Unforunately though, not all plugins follow this pattern.  For instance, I just checked `Leaflet-minimap`, and everything is in `/dist` as discussed, but `Leaflet-graticule` and `Leaflet-Simplegraticule` don't have a `package.json`.  `Proj4Leaflet` is on unpkg, but the js is in `/src/`.

I would like to use the ithub API, but most repos don't store the bundled JS/CSS within the repo.

Would love to help figure out a workflow for this so am eager to hear your thoughts.

Not directly applicable, but here is what I have for `reactR` [build.R](https://github.com/timelyportfolio/reactR/blob/master/build/getreact.R).

**Comment by schloerke** [comment]
So far I have been using npm (w/ napa) and webpack. in leaflet.extras.  

* npm to know exactly where things are being installed from. 
* napa (a npm package) to install two libraries that don't contain a package.json file. (Which we then require the .js file directly)
* Webpack to combine files/css and make sure all files exist, which is a great reassurance.  

I think Webpack is a little overkill, as a a script like your build.R would suffic, but both are better than copypasta'ing library files. (Which is the current state for leaflet, leaflet.extra, leaflet.esri.)

I'm keen to maybe explore Webpack a little more to see how I can trim it down to a reasonable size config file.  While I enjoy the single file utility of unpkg.com, it becomes a little harder with css and, like you said, non pre-bundled distributions.

**Comment by schloerke** [comment]
Currently, since leaflet is working as is, I am waiting to upgrade until the next release.  We will use leaflet.extras and leaflet.esri as test packages.

**Comment by schloerke** [comment]
closing as webpack was used to bundle everything into a build folder.

**Pull request closed without merging**
